version: 3

paths:
  exclude:
    - ./NOTICE.txt
vendoredDependencies:
  licenseScanPathFilters:
    exclude:
      - "frontend/src/lib/codemirror/themes/**/*"
targets:
  exclude:
    - type: setuptools
      path: hack/icon
    - type: npm
      path: frontend/wailsjs/runtime
    - type: pnpm
      path: .mcp/flowbite-svelte-mcp
