# Copyright 2026 raml-dev
# SPDX-License-Identifier: GPL-2.0-or-later

[tasks."ci:fe:install"]
dir = "{{ config_root }}/frontend"
run = "npm install"

[tasks."ci:fe:lint"]
dir = "{{ config_root }}/frontend"
run = "npm run lint"

[tasks."ci:fe:check"]
dir = "{{ config_root }}/frontend"
run = "wails generate module && npm run check"

[tasks."ci:be:build"]
run = "wails build -tags webkit2_41"

[tasks."ci:be:test"]
run = "go test -v ./..."

# Development task definitions
[tasks."ci:check-license"]
description = "Check license headers in all files"
run = """
addlicense -check -c "raml-dev" -v -s -l GPL-3.0-only -ignore frontend/node_modules/* ./frontend ./internal go.mod go.sum *.go
"""
