# Copyright 2026-present raml-dev
# SPDX-License-Identifier: GPL-3.0-only

[tools]
go = "1.25.6"
"go:github.com/raml-dev/addlicense" = "1.0.0"
"go:mvdan.cc/garble" = "0.15.0"
"go:github.com/wailsapp/wails/v2/cmd/wails" = "2.11.0"
node = "24.12.0"
