// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
import { jsonHighlighting } from "./highlight";
import { variableTokens } from "./tokens";
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "$hOVQROOOOQO'#Cc'#CcOqQQO'#CfOyQRO'#CmOOQO'#Cn'#CnOOQO'#Ct'#CtQOQQOOOOQO'#Ch'#ChO!QQQO'#CgO!VQQO'#CvOOQO,59Q,59QO!_QQO,59QO!dQQO'#CwOOQO,59X,59XO!lQQO,59XOVQRO,59ROtQQO'#CoO!qQQO,59bOOQO1G.l1G.lOVQRO'#CpO!yQQO,59cOOQO1G.s1G.sOOQO1G.m1G.mOOQO,59Z,59ZOOQO-E6m-E6mOOQO,59[,59[OOQO-E6n-E6n",
  stateData:
    "#R~OgOS~OPSORTOSTOTTOUTOXQO`ROiPO~OWYOiVO~O_]O~PVO]_O~O^`OWjX~OWbO~O^cO_kX~O_eO~O^`OWja~O^cO_ka~O",
  goto: "!mlPPPPPPPmPPmsyPPPPmm}!TPPP!ZP!g!jXTOR_cQXQRg`TWQ`QaXRhaQd[RjdQUOQ[RQf_RicRZQR^R",
  nodeNames:
    "⚠ VariableRef JsonText True False Null Number String } { Object Property PropertyName : , ] [ Array VariableRef",
  maxTerm: 27,
  nodeProps: [
    ["isolate", -3, 7, 12, 18, ""],
    ["openedBy", 8, "{", 15, "["],
    ["closedBy", 9, "}", 16, "]"]
  ],
  propSources: [jsonHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData:
    "(|~RaXY!WYZ!W]^!Wpq!Wrs!]|}$u}!O$z!Q!R%T!R![&c![!]&t!}#O&y#P#Q'O#Y#Z'T#b#c'r#h#i(Z#o#p(r#q#r(w~!]Og~~!`Wpq!]qr!]rs!xs#O!]#O#P!}#P;'S!];'S;=`$o<%lO!]~!}Oi~~#QXrs!]!P!Q!]#O#P!]#U#V!]#Y#Z!]#b#c!]#f#g!]#h#i!]#i#j#m~#pR!Q![#y!c!i#y#T#Z#y~#|R!Q![$V!c!i$V#T#Z$V~$YR!Q![$c!c!i$c#T#Z$c~$fR!Q![!]!c!i!]#T#Z!]~$rP;=`<%l!]~$zO^~~$}Q!Q!R%T!R![&c~%YRU~!O!P%c!g!h%w#X#Y%w~%fP!Q![%i~%nRU~!Q![%i!g!h%w#X#Y%w~%zR{|&T}!O&T!Q![&Z~&WP!Q![&Z~&`PU~!Q![&Z~&hSU~!O!P%c!Q![&c!g!h%w#X#Y%w~&yO]~~'OO`~~'TO_~~'WP#T#U'Z~'^P#`#a'a~'dP#g#h'g~'jP#X#Y'm~'rOS~~'uP#i#j'x~'{P#`#a(O~(RP#`#a(U~(ZOT~~(^P#f#g(a~(dP#i#j(g~(jP#X#Y(m~(rOR~~(wOX~~(|OW~",
  tokenizers: [variableTokens, 0],
  topRules: { JsonText: [0, 2] },
  tokenPrec: 0
});
