// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRequest(arg1, arg2) {
  return window['go']['main']['App']['AddRequest'](arg1, arg2);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteCustomTheme(arg1) {
  return window['go']['main']['App']['DeleteCustomTheme'](arg1);
}

export function Execute(arg1) {
  return window['go']['main']['App']['Execute'](arg1);
}

export function GetActiveTheme() {
  return window['go']['main']['App']['GetActiveTheme']();
}

export function GetAllThemes() {
  return window['go']['main']['App']['GetAllThemes']();
}

export function GetCustomThemes() {
  return window['go']['main']['App']['GetCustomThemes']();
}

export function GetPredefinedThemes() {
  return window['go']['main']['App']['GetPredefinedThemes']();
}

export function GetRequests(arg1) {
  return window['go']['main']['App']['GetRequests'](arg1);
}

export function GetThemeByName(arg1) {
  return window['go']['main']['App']['GetThemeByName'](arg1);
}

export function LoadCollection(arg1) {
  return window['go']['main']['App']['LoadCollection'](arg1);
}

export function LoadCollections() {
  return window['go']['main']['App']['LoadCollections']();
}

export function RemoveRequest(arg1, arg2) {
  return window['go']['main']['App']['RemoveRequest'](arg1, arg2);
}

export function SaveCustomTheme(arg1) {
  return window['go']['main']['App']['SaveCustomTheme'](arg1);
}

export function SetActiveTheme(arg1) {
  return window['go']['main']['App']['SetActiveTheme'](arg1);
}

export function UpdateCollection(arg1) {
  return window['go']['main']['App']['UpdateCollection'](arg1);
}

export function UpdateRequest(arg1, arg2) {
  return window['go']['main']['App']['UpdateRequest'](arg1, arg2);
}
