// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {environment} from '../models';
import {main} from '../models';
import {requester} from '../models';
import {theme} from '../models';

export function AddRequest(arg1:string,arg2:collection.Request):Promise<void>;

export function AddValue(arg1:string,arg2:string,arg3:environment.ValueType):Promise<void>;

export function CreateCollection(arg1:string):Promise<void>;

export function CreateEnvironment(arg1:string):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteCustomTheme(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function Execute(arg1:main.RequestOptions):Promise<requester.ResponseData>;

export function GetActiveTheme():Promise<string>;

export function GetAllThemes():Promise<Array<theme.Theme>>;

export function GetCustomThemes():Promise<Array<theme.Theme>>;

export function GetPredefinedThemes():Promise<Array<theme.Theme>>;

export function GetRequests(arg1:string):Promise<any>;

export function GetThemeByName(arg1:string):Promise<theme.Theme>;

export function GetValues(arg1:string):Promise<any>;

export function LoadCollection(arg1:string):Promise<collection.Collection>;

export function LoadCollections():Promise<any>;

export function LoadEnvironment(arg1:string):Promise<environment.Environment>;

export function LoadEnvironments():Promise<any>;

export function RemoveRequest(arg1:string,arg2:string):Promise<void>;

export function RemoveValue(arg1:string,arg2:string):Promise<void>;

export function ResolveRequestPlaceholders(arg1:string,arg2:string,arg3:string):Promise<any>;

export function SaveCustomTheme(arg1:theme.Theme):Promise<void>;

export function SetActiveTheme(arg1:string):Promise<void>;

export function UpdateCollection(arg1:collection.Collection):Promise<void>;

export function UpdateEnvironment(arg1:environment.Environment):Promise<void>;

export function UpdateRequest(arg1:string,arg2:collection.Request):Promise<void>;

export function UpdateValue(arg1:string,arg2:string,arg3:environment.ValueType):Promise<void>;
