// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCustomTheme(arg1) {
  return window['go']['main']['App']['DeleteCustomTheme'](arg1);
}

export function Execute(arg1) {
  return window['go']['main']['App']['Execute'](arg1);
}

export function GetActiveTheme() {
  return window['go']['main']['App']['GetActiveTheme']();
}

export function GetAllThemes() {
  return window['go']['main']['App']['GetAllThemes']();
}

export function GetCustomThemes() {
  return window['go']['main']['App']['GetCustomThemes']();
}

export function GetPredefinedThemes() {
  return window['go']['main']['App']['GetPredefinedThemes']();
}

export function GetThemeByName(arg1) {
  return window['go']['main']['App']['GetThemeByName'](arg1);
}

export function SaveCustomTheme(arg1) {
  return window['go']['main']['App']['SaveCustomTheme'](arg1);
}

export function SetActiveTheme(arg1) {
  return window['go']['main']['App']['SetActiveTheme'](arg1);
}
