// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {theme} from '../models';

export function DeleteCustomTheme(arg1:string):Promise<void>;

export function Execute(arg1:main.RequestOptions):Promise<main.ResponseData>;

export function GetActiveTheme():Promise<string>;

export function GetAllThemes():Promise<Array<theme.Theme>>;

export function GetCustomThemes():Promise<Array<theme.Theme>>;

export function GetPredefinedThemes():Promise<Array<theme.Theme>>;

export function GetThemeByName(arg1:string):Promise<theme.Theme>;

export function SaveCustomTheme(arg1:theme.Theme):Promise<void>;

export function SetActiveTheme(arg1:string):Promise<void>;
