name: ci

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "docs/**"

# cancel in-progress runs when a new commit is pushed to the same PR
concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Outputs variables to decide which jobs to run after this
  changes:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      ci: ${{ steps.filter.outputs.ci }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'internal/**'
            ci:
              - '.github/**'
              - 'mise.toml'
              - 'mise.ci.toml'

  test-frontend:
    needs: [changes]
    if: needs.changes.outputs.frontend == 'true' || needs.changes.outputs.ci == 'true'
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    env:
      MISE_ENV: ci
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          cache_key: "mise-{{platform}}-{{version}}-{{file_hash}}"
          install: false
      # https://github.com/actions/cache/blob/main/examples.md#node---npm
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v5
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Frontend checks - install
        run: mise run ci:fe:install
      - name: Frontend checks - eslint
        run: mise run ci:fe:lint
      - name: Frontend checks - svelte-check
        run: mise run ci:fe:check

  test-backend:
    needs: [changes]
    if: needs.changes.outputs.backend == 'true' || needs.changes.outputs.ci == 'true'
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    env:
      MISE_ENV: ci
    steps:
      - uses: actions/checkout@v6
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-0 libwebkit2gtk-4.1-dev
          version: 1.0
      # https://github.com/actions/cache/blob/main/examples.md#node---npm
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v5
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: jdx/mise-action@v4
        with:
          cache_key: "mise-{{platform}}-{{version}}-{{file_hash}}"
          install: false
      # https://github.com/actions/cache/blob/main/examples.md#go---modules
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Backend checks - Wails build
        run: mise run ci:be:build
      - name: Backend checks - Go tests
        run: mise run ci:be:tests
